Use Async when Connecting i3ipc
infokiller/i3-workspace-groups pull request #59
Opened 2023-03-24 07:10 UTC by rt-kill

I was getting some errors when calling this script because i3 was being used before it was fully connected. Following the [example](https://github.com/altdesktop/i3ipc-python#asyncio-support), these can be averted by awaiting the connection.

It also seems about time to switch from the deprecated hook calls.

2023-03-24 08:01 UTC, infokiller requested changes
Thanks for the PR!
Some comments inside

2023-03-24 19:24 UTC, rt-kill commented on scripts/i3-groups-polybar-module-updater
> +    loop.run_until_complete(main())
👍 No real reason, I had just read this somewhere and am not familiar with the library.

2023-03-24 19:24 UTC, rt-kill commented on scripts/i3-groups-polybar-module-updater
> -    subprocess.run(['polybar-msg', 'hook', 'i3-mod', '1'], check=False)
Sounds good, will do

2023-03-25 07:30 UTC, infokiller commented
Thanks a lot for the contribution!

2023-03-25 07:30 UTC, merged